language: node_js

node_js:
  - '8'

os:
  - linux
  - osx
  - windows

install:
  - npm install

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install -y rpm;
    fi

script:
  - npm run lint
  - npm run test
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      npm run release;
      npm run deploy;
    else
      npm run build-prod;
    fi

branches:
  only:
  - master
  - develop
  - support-CD

env:
  secure: Zsp9KpQaFgyK5luPmvfm6J+7Pcp3VcMrkCKbWTLXhj+xl9ecE71rXK3Ai6fgNcMa8JE8io4PsGUbBLm7dNQEmtRcn7c0QsjturUDI8l46voyhwjXTNUi7Pd8q+/RpPjD7+Tme738FVtRwtmW+63BQRaS8gmlz20igrfjb8azQ2Z4NdEN8rhdgzmFglgvnnYC4ygCSNcYjWw769A8wMWDkgzhBL8DkgPZPo2uAYuANL8LLG433S1bceU/Fi++AGBodo4s9A06V6qSiLugwTE6bucl/FkwzPSjtcfbkZZ6HnOiNWcncD0kiQP8APGP7Sg+7w5wXHIkAk9CfqSVcnxmk8bgUJZgbHerr48+XHEjPTeJYzHww8BgO0MgsynMgCiXdUXIuQghSJBSG0bU8qvdF/X8TXLnyp2t7oPL248Hgi8iNTdzeyDJvc/Oa29R+DPTrPT+svuux4qsl0GKk2jFyHnqaU5PpOD8CfGHxTVh7hWXnv1n/gvc0hfdIcnDah9vIsn7Gu0uKIWrDVx024Ins+jCkERe5zyKsXXm/RKBTiNBSjj3nWhV3dmqLS1ggU/fzLhdyC73bwky7z0EBXgw92sPAZR2eOEmQfMb1EkDOKlNl1kciR1qUC90u8USIIGm4r9s83rrADCxU6/04aIrIwn+NNkc+Tu+cuqvHHgxP0o=
